language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

branches:
  except:
  - dev
  only:
  - master

script:
  - docker --version # print the version for logging
  - docker build -t simple-express .
  - docker tag simple-express mtsowm/udacity-simple-express:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push simple-express mtsowm/udacity-simple-express

